return {
    "TotalDPS",
    "CombinedDPS",
    "Life",
    "EnergyShield",
    "Mana",
    "Armour",
    "Evasion",
    "FireResist",
    "ColdResist",
    "LightningResist",
    "ChaosResist",
    "SpellSuppressionChance",
    "BlockChance",
    "SpellBlockChance",
}
